# Generated by Django 3.0.8 on 2020-08-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200810_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability', models.CharField(choices=[('HE', 'Discapacidad Auditiva'), ('PH', 'Discapacidad Física'), ('IN', 'Discapacidad Intelectual'), ('LA', 'Discapacidad del Lenguaje'), ('PS', 'Discapacidad Psicosocial'), ('VI', 'Discapacidad Visual')], max_length=2)),
                ('category', models.CharField(choices=[('AC', 'Actividades recreativas'), ('PC', 'Cuidado personal')], max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1500)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Representative_Patient',
            new_name='Relationship',
        ),
        migrations.CreateModel(
            name='Therapy_local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_date', models.DateField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_date', models.DateField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='Therapeutic_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number_1', models.PositiveIntegerField()),
                ('phone_number_2', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=10)),
                ('bank_id_card', models.CharField(max_length=10)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like', models.PositiveIntegerField()),
                ('dislike', models.IntegerField()),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Forum_entry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Direction')),
            ],
        ),
    ]
