# Generated by Django 3.0.8 on 2020-08-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disability_card',
            old_name='disability',
            new_name='disability_type',
        ),
        migrations.AddField(
            model_name='disability_card',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Patient'),
        ),
        migrations.AlterField(
            model_name='forum_response',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forum_response',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
