# Generated by Django 3.0.8 on 2020-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200822_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disability_card',
        ),
    ]
