# Generated by Django 3.0.8 on 2020-08-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0010_auto_20200825_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_street', models.CharField(max_length=250)),
                ('secondary_street', models.CharField(max_length=250, null=True)),
                ('house_number', models.CharField(max_length=5, null=True)),
                ('reference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('identity_card', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('country_origin', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=100)),
                ('canton', models.CharField(max_length=100)),
                ('educational_institution_type', models.CharField(choices=[('IN', 'Inclusiva'), ('SP', 'Especializada'), ('RE', 'Regular')], default='SP', max_length=2)),
                ('educational_institution', models.CharField(max_length=400)),
                ('parish_type', models.CharField(choices=[('UB', 'Urbana'), ('RU', 'Rural')], default='UB', max_length=2)),
                ('bond_desarrollo_humano', models.BooleanField()),
                ('bond_joaquin_gallegos', models.BooleanField()),
                ('alimony', models.BooleanField()),
                ('jubilee_pension', models.BooleanField()),
                ('montepio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability', models.CharField(choices=[('HE', 'Discapacidad Auditiva'), ('PH', 'Discapacidad Física'), ('IN', 'Discapacidad Intelectual'), ('LA', 'Discapacidad del Lenguaje'), ('PS', 'Discapacidad Psicosocial'), ('VI', 'Discapacidad Visual')], max_length=2)),
                ('category', models.CharField(choices=[('AC', 'Actividades recreativas'), ('PC', 'Cuidado personal')], max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1500)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('identity_card', models.CharField(max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('TR', 'Terapeuta'), ('RP', 'Representante')], default='RP', max_length=2)),
                ('birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('civil_status', models.CharField(max_length=150)),
                ('phone_number_1', models.PositiveIntegerField()),
                ('phone_number_2', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=500)),
                ('degree', models.CharField(max_length=500)),
                ('biography', models.TextField()),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_date', models.DateField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='Therapy_live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy_date', models.DateField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.CreateModel(
            name='Therapeutic_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number_1', models.PositiveIntegerField()),
                ('phone_number_2', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=10)),
                ('bank_id_card', models.CharField(max_length=10)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='representatives',
            field=models.ManyToManyField(through='website.Relationship', to='website.User'),
        ),
        migrations.CreateModel(
            name='Forum_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like', models.PositiveIntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Forum_entry')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.User')),
            ],
        ),
        migrations.AddField(
            model_name='forum_entry',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.User'),
        ),
        migrations.CreateModel(
            name='Disability_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(choices=[('HE', 'Discapacidad Auditiva'), ('PH', 'Discapacidad Física'), ('IN', 'Discapacidad Intelectual'), ('LA', 'Discapacidad del Lenguaje'), ('PS', 'Discapacidad Psicosocial'), ('VI', 'Discapacidad Visual')], max_length=2)),
                ('disability_description', models.TextField()),
                ('disability_percentage', models.PositiveSmallIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Direction')),
            ],
        ),
    ]
