# Generated by Django 3.0.8 on 2020-09-05 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200904_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=30)),
                ('disability_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='disability_card',
            name='disability_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Disability'),
        ),
    ]
