# Generated by Django 3.0.8 on 2020-09-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200904_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_response',
            name='response',
            field=models.TextField(max_length=5000),
        ),
    ]
