# Generated by Django 3.0.8 on 2020-09-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200905_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_local',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AlterField(
            model_name='therapy_local',
            name='therapy_date',
            field=models.CharField(max_length=500),
        ),
    ]
