# Generated by Django 3.0.7 on 2020-09-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200908_1347'),
        ('website', '0017_auto_20200907_1844'),
    ]

    operations = [
    ]
