# Generated by Django 3.0.8 on 2020-09-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_merge_20200908_1758'),
        ('website', '0018_merge_20200908_1425'),
    ]

    operations = [
    ]
