# Generated by Django 3.0.7 on 2020-09-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_merge_20200908_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability_card',
            name='disability_type',
            field=models.CharField(choices=[('HE', 'Discapacidad Auditiva'), ('PH', 'Discapacidad Física'), ('IN', 'Discapacidad Intelectual'), ('LA', 'Discapacidad del Lenguaje'), ('PS', 'Discapacidad Psicosocial'), ('VI', 'Discapacidad Visual')], max_length=2),
        ),
    ]
