# Generated by Django 3.0.7 on 2020-09-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200909_0325'),
        ('website', '0020_auto_20200908_1852'),
    ]

    operations = [
    ]
