# Generated by Django 3.0.7 on 2020-09-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_merge_20200909_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_live',
            name='therapy_day',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='MON', max_length=15),
        ),
    ]
