# Generated by Django 3.0.8 on 2020-09-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_merge_20200909_0440'),
        ('website', '0023_auto_20200909_0412'),
    ]

    operations = [
    ]
