# Generated by Django 3.0.7 on 2020-09-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200909_1527'),
        ('website', '0024_merge_20200909_0521'),
    ]

    operations = [
    ]
