# Generated by Django 3.0.7 on 2020-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_merge_20200909_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy_live',
            name='therapy_day',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=15),
        ),
    ]
